### ISSUE TITLE
No info shown on Getting started section.

### ISSUE THREAD

**Issue by simarpreetsingh-019** [SenseNet/docs.sensenet.com#117]
## Error reporting :
There is no info when clicking on tutorial section and then on getting started section. nav bars and sidebars there, but no info regarding how it works.

is it still under process or is this an error?

## how to reproduce the error : 
visit : https://docs.sensenet.com/tutorials/getting-started

only edit on github button is shown only.

**Comment by herflis** [comment]
@simarpreetsingh-019 yes, it is in progress, but thanks for reporting this 👍
