### ISSUE TITLE
[BUG] logo font issue on docs.sensenet.com

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/docs.sensenet.com#146]
I've noticed some anomaly with the logo font on docs.sensenet.com.

**Browser:** Google Chrome (windows) - Version 87.0.4280.66 (Official Build) (64-bit)

It seems like the logo has the Roboto Light font family accidentally. (see screenshots below)

## original
![image](https://user-images.githubusercontent.com/19875603/100091217-9e209c80-2e54-11eb-8e32-798b98d09c31.png)

![image](https://user-images.githubusercontent.com/19875603/100091124-7d584700-2e54-11eb-81e0-895e214a219a.png)

## how it should be (as far as I know)
![image](https://user-images.githubusercontent.com/19875603/100091193-96f98e80-2e54-11eb-8c8f-3720adbf67d5.png)

![image](https://user-images.githubusercontent.com/19875603/100091177-8fd28080-2e54-11eb-956a-2586875df40d.png)

**Comment by herflis** [comment]
@huszerlbence I cannot reproduce this issue 😿
