### ISSUE TITLE
Gatsby source starter

### ISSUE THREAD

**Issue by herflis** [SenseNet/docs.sensenet.com#169]
Starters help devs create a new Gatsby site quickly. They also provide working examples for config and code to help devs learn about and play with your source plugin. Check out our [Creating a Starter](https://www.gatsbyjs.com/docs/creating-a-starter/) doc for more details.

**Comment by pusztaienike** [comment]
PR: https://github.com/SenseNet/gatsby-starter-sensenet-blog/pull/1
